local addonName, addonTable = ...

local L = LibStub("AceLocale-3.0"):GetLocale("Rarity")
local CONSTANTS = addonTable.constants

if LE_EXPANSION_LEVEL_CURRENT < LE_EXPANSION_WAR_WITHIN then
	return {}
end

local twwPets = {
	-- 11.0 pets
	["Bop"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Bop"],
		npcs = { 218523, 214661 },
		itemId = 223155,
		spellId = 446024,
		chance = 30,
		creatureId = 222318,
		groupSize = 5,
		equalOdds = true,
		instanceDifficulties = { [CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true },
		coords = { { m = CONSTANTS.UIMAPIDS.CINDERBREW_MEADERY, i = true } },
	},
	["Writhing Transmutagen"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.SPECIAL,
		name = L["Writhing Transmutagen"],
		itemId = 223487,
		spellId = 446059,
		chance = 1000,
		creatureId = 222359,
	},
	-- 11.0.7 pets
	["Crackleroar"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		chance = 100,
		creatureId = 235124,
		itemId = 234379,
		name = L["Crackleroar"],
		npcs = { 230827, 231353 },
		spellId = 1213821,
		coords = { { m = CONSTANTS.UIMAPIDS.SIREN_ISLE } },
	},
	["Proper Parrot"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		chance = 100,
		creatureId = 148542,
		itemId = 166358,
		name = L["Proper Parrot"],
		npcs = { 229169, 227644, 229189, 229171, 228582, 229168, 228583, 228580, 229190 },
		spellId = 288054,
		coords = { { m = CONSTANTS.UIMAPIDS.SIREN_ISLE } },
	},
	-- 11.1 pets
	["Craboom"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.BOSS,
		name = L["Craboom"],
		chance = 5,
		creatureId = 238393,
		itemId = 236768,
		npcs = { 226396 },
		spellId = 1220834,
		coords = { { m = CONSTANTS.UIMAPIDS.OPERATION_FLOODGATE } },
		groupSize = 5,
		equalOdds = true,
	},
	["Viridian Mechasaur"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 33,
		creatureId = 231456,
		name = L["Viridian Mechasaur"],
		itemId = 232838,
		items = { 233557 },
		spellId = 471944,
		coords = { { m = CONSTANTS.UIMAPIDS.UNDERMINE, x = 25.6, y = 38.2, n = L["Angelo Rustbin"] } },
	},
	["Parrot Cage (Void-Scarred Parrot)"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.SPECIAL,
		chance = 12,
		creatureId = 237852,
		name = L["Parrot Cage (Void-Scarred Parrot)"],
		itemId = 235793,
		spellId = 1218379,
		coords = { { m = CONSTANTS.UIMAPIDS.HORRIFIC_REVISION_OF_STORMWIND } },
	},
	["Eye of Chaos"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.SPECIAL,
		chance = 12,
		creatureId = 237850,
		name = L["Eye of Chaos"],
		itemId = 235794,
		spellId = 1218378,
		coords = { { m = CONSTANTS.UIMAPIDS.HORRIFIC_REVISION_OF_STORMWIND } },
	},
	["Void Scarred Scorpid"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.SPECIAL,
		chance = 12,
		creatureId = 237855,
		name = L["Void Scarred Scorpid"],
		itemId = 235795,
		spellId = 1218381,
		coords = { { m = CONSTANTS.UIMAPIDS.HORRIFIC_REVISION_OF_ORGRIMMAR } },
	},
	["Void-Scarred Egg"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.SPECIAL,
		chance = 12,
		creatureId = 237856,
		name = L["Void-Scarred Egg"],
		itemId = 235797,
		spellId = 1218383,
		coords = { { m = CONSTANTS.UIMAPIDS.HORRIFIC_REVISION_OF_ORGRIMMAR } },
	},
	-- 11.2 pets
	["Duskthief"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		chance = 5,
		creatureId = 245500,
		itemId = 245254,
		name = L["Duskthief"],
		npcs = { 232111 },
		spellId = 1238336,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Heka'Tarnos, Bringer of Discord"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		chance = 5,
		creatureId = 245504,
		itemId = 245272,
		name = L["Heka'Tarnos, Bringer of Discord"],
		npcs = { 245998 },
		spellId = 1238338,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Palek'ti, the Mouth of Nothingness"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		chance = 5,
		creatureId = 245496,
		itemId = 245214,
		name = L["Palek'ti, the Mouth of Nothingness"],
		npcs = { 245997 },
		spellId = 1238330,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Jimmy"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		chance = 5,
		creatureId = 245481,
		itemId = 244915,
		name = L["Jimmy"],
		npcs = { 232108 },
		spellId = 1238283,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Cerulean Lapbug"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245506,
		name = L["Cerulean Lapbug"],
		itemId = 245274,
		items = { 245611 },
		spellId = 1238346,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Copper Lapbug"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245505,
		name = L["Copper Lapbug"],
		itemId = 245273,
		items = { 245611 },
		spellId = 1238341,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Cyan Siphonmite"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245482,
		name = L["Cyan Siphonmite"],
		itemId = 244916,
		items = { 245611 },
		spellId = 1238284,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Dread Horrorling"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245474,
		name = L["Dread Horrorling"],
		itemId = 244907,
		items = { 245611 },
		spellId = 1238270,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Graceful Cosmic Ray Pup"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245498,
		name = L["Graceful Cosmic Ray Pup"],
		itemId = 245252,
		items = { 245611 },
		spellId = 1238332,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Impartial Watcher"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245475,
		name = L["Impartial Watcher"],
		itemId = 244909,
		items = { 245611 },
		spellId = 1238271,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Inquisitive Cosmic Ray Pup"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245502,
		name = L["Inquisitive Cosmic Ray Pup"],
		itemId = 245253,
		items = { 245611 },
		spellId = 1238335,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Scrappy Thorntail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245217,
		name = L["Scrappy Thorntail"],
		itemId = 244468,
		items = { 245611 },
		spellId = 1237379,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Shimmering Inchshifter"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245497,
		name = L["Shimmering Inchshifter"],
		itemId = 245215,
		items = { 245611 },
		spellId = 1238331,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Veridian Thorntail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245215,
		name = L["Veridian Thorntail"],
		itemId = 244467,
		items = { 245611 },
		spellId = 1237377,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Vitriolic Inchshifter"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245494,
		name = L["Vitriolic Inchshifter"],
		itemId = 245212,
		items = { 245611 },
		spellId = 1238328,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
	["Xanthous Siphonmite"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.TWW,
		type = CONSTANTS.ITEM_TYPES.PET,
		method = CONSTANTS.DETECTION_METHODS.USE,
		chance = 5,
		creatureId = 245480,
		name = L["Xanthous Siphonmite"],
		itemId = 244914,
		items = { 245611 },
		spellId = 1238282,
		coords = { { m = CONSTANTS.UIMAPIDS.KARESH } },
	},
}

Rarity.ItemDB.MergeItems(Rarity.ItemDB.pets, twwPets)
return twwPets
