local addonName, addonTable = ...

local L = LibStub("AceLocale-3.0"):GetLocale("Rarity")
local CONSTANTS = addonTable.constants

if LE_EXPANSION_LEVEL_CURRENT < LE_EXPANSION_WARLORDS_OF_DRAENOR then
	return {}
end

local holidayEventToysWoD = {
	["Coin of Many Faces"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Coin of Many Faces"],
		itemId = 128807,
		npcs = { 96535, 96538, 96637, 96536 },
		chance = 100,
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.HALLOWS_END,
		coords = { { m = 104, x = 40.6, y = 79.4 } },
	},
	["Crashin' Thrashin' Flamer Controller"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Crashin' Thrashin' Flamer Controller"],
		itemId = 108632,
		items = { 116762 },
		chance = 50,
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.WINTERS_VEIL,
		questId = { 6983, 7043 },
		coords = { { m = CONSTANTS.UIMAPIDS.HILLSBRAD_FOOTHILLS, x = 43.6, y = 39.6 } },
	},
	["Crashin' Thrashin' Shredder Controller"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Crashin' Thrashin' Shredder Controller"],
		itemId = 116763,
		items = { 116762 },
		chance = 50,
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.WINTERS_VEIL,
		questId = { 6983, 7043 },
		coords = { { m = CONSTANTS.UIMAPIDS.HILLSBRAD_FOOTHILLS, x = 43.6, y = 39.6 } },
	},
	["Endothermic Blaster"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Endothermic Blaster"],
		itemId = 128636,
		items = { 116762 },
		chance = 200, -- Guess
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.WINTERS_VEIL,
		questId = { 6983, 7043 },
		coords = { { m = CONSTANTS.UIMAPIDS.HILLSBRAD_FOOTHILLS, x = 43.6, y = 39.6 } },
	},
	["Fuzzy Green Lounge Cushion"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Fuzzy Green Lounge Cushion"],
		itemId = 116692,
		items = { 21271, 21270, 116762 },
		chance = 100,
		sourceText = L["Available starting December 25th"],
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.WINTERS_VEIL,
		questId = { 8788, 8767 },
		coords = { { m = 86, x = 49.1, y = 78.2, h = true }, { m = 87, x = 33.4, y = 65.9, a = true } },
	},
	["Pineapple Lounge Cushion"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Pineapple Lounge Cushion"],
		itemId = 116689,
		items = { 21271, 21270, 116762 },
		chance = 100,
		sourceText = L["Available starting December 25th"],
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.WINTERS_VEIL,
		questId = { 8788, 8767 },
		coords = { { m = 86, x = 49.1, y = 78.2, h = true }, { m = 87, x = 33.4, y = 65.9, a = true } },
	},
	["Red Wooden Sled"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Red Wooden Sled"],
		itemId = 128776,
		items = { 116762 },
		chance = 50,
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.WINTERS_VEIL,
		questId = { 6983, 7043 },
		coords = { { m = CONSTANTS.UIMAPIDS.HILLSBRAD_FOOTHILLS, x = 43.6, y = 39.6 } },
	},
	["Sack of Spectral Spiders"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Sack of Spectral Spiders"],
		itemId = 128794,
		npcs = { 96323 },
		chance = 8,
		questId = 39617,
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.HALLOWS_END,
		coords = { zoneOverride = L["Draenor Garrison"], { m = 579 }, { m = 585 } },
	},
	["Safari Lounge Cushion"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Safari Lounge Cushion"],
		itemId = 116690,
		items = { 21271, 21270, 116762 },
		chance = 100,
		sourceText = L["Available starting December 25th"],
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.WINTERS_VEIL,
		questId = { 8788, 8767 },
		coords = { { m = 86, x = 49.1, y = 78.2, h = true }, { m = 87, x = 33.4, y = 65.9, a = true } },
	},
	["Scroll of Storytelling"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Scroll of Storytelling"],
		itemId = 116456,
		items = { 116762 },
		chance = 8,
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.WINTERS_VEIL,
		questId = { 6983, 7043 },
		coords = { { m = CONSTANTS.UIMAPIDS.HILLSBRAD_FOOTHILLS, x = 43.6, y = 39.6 } },
	},
	["Silver-Plated Turkey Shooter"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Silver-Plated Turkey Shooter"],
		itemId = 116400,
		items = { 116404 },
		chance = 33,
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.PILGRIMS_BOUNTY,
		coords = {
			{ m = 87, x = 60, y = 34.2, q = 14048, a = true },
			{ m = 87, x = 60, y = 34.2, q = 14051, a = true },
			{ m = 89, x = 61.8, y = 46.4, q = 14054, a = true },
			{ m = 37, x = 33.8, y = 50.8, q = 14055, a = true },
			{ m = 37, x = 33.6, y = 50.6, q = 14053, a = true },
			{ m = 1, x = 46.4, y = 13.8, q = 14061, h = true },
			{ m = 1, x = 46.4, y = 13.8, q = 14062, h = true },
			{ m = 88, x = 31, y = 69.6, q = 14060, h = true },
			{ m = 998, x = 65.2, y = 13.8, q = 14058, h = true },
			{ m = 998, x = 63.4, y = 9, q = 14059, h = true },
		},
	},
	["Zhevra Lounge Cushion"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.HOLIDAY,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		isToy = true,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Zhevra Lounge Cushion"],
		itemId = 116691,
		items = { 21271, 21270, 116762 },
		chance = 100,
		sourceText = L["Available starting December 25th"],
		holidayTexture = CONSTANTS.HOLIDAY_TEXTURES.WINTERS_VEIL,
		questId = { 8788, 8767 },
		coords = { { m = 86, x = 49.1, y = 78.2, h = true }, { m = 87, x = 33.4, y = 65.9, a = true } },
	},
}

Rarity.ItemDB.MergeItems(Rarity.ItemDB.toys, holidayEventToysWoD)
return holidayEventToysWoD
