local addonName, addonTable = ...

local L = LibStub("AceLocale-3.0"):GetLocale("Rarity")
local CONSTANTS = addonTable.constants

if not LE_EXPANSION_MIDNIGHT or LE_EXPANSION_LEVEL_CURRENT < LE_EXPANSION_MIDNIGHT then
	return {}
end

local midnightToys = {
	["Saptor Salve"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Saptor Salve"],
		itemId = 268728,
		tooltipNpcs = { 247676 },
		npcs = { 99999 },
		statisticId = { 61661 },
		groupSize = 5,
		equalOdds = true,
		chance = 20,
		instanceDifficulties = { [CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true },
		coords = { { m = CONSTANTS.UIMAPIDS.BLINDING_VALE, i = true } },
	},
	["Cosmic Ritual Stone"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		method = CONSTANTS.DETECTION_METHODS.BOSS,
		name = L["Cosmic Ritual Stone"],
		itemId = 264672,
		chance = 25,
		npcs = { 99999 },
		tooltipNpcs = { 240432 },
		lockBossName = "Fallen-King Salhadaar",
		statisticId = { 61287, 61284, 61285, 61286 },
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.LFR] = true,
		},
		coords = { { i = true, m = CONSTANTS.UIMAPIDS.VOIDSPIRE } },
		groupSize = 25,
		equalOdds = true,
	},
	["Madcap Redcap"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		method = CONSTANTS.DETECTION_METHODS.BOSS,
		name = L["Madcap Redcap"],
		itemId = 264313,
		chance = 25,
		npcs = { 99999 },
		tooltipNpcs = { 254176 },
		lockBossName = "Rotmire",
		statisticId = { 63233, 63234, 63235, 63236 },
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.LFR] = true,
		},
		coords = { { i = true, m = CONSTANTS.UIMAPIDS.SPOREFALL } },
		groupSize = 25,
		equalOdds = true,
	},
	["Mycomancer's Hearthspore"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
		type = CONSTANTS.ITEM_TYPES.ITEM,
		method = CONSTANTS.DETECTION_METHODS.BOSS,
		name = L["Mycomancer's Hearthspore"],
		itemId = 264367,
		chance = 25,
		npcs = { 99999 },
		tooltipNpcs = { 254176 },
		lockBossName = "Rotmire",
		statisticId = { 63233, 63234, 63235, 63236 },
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.LFR] = true,
		},
		coords = { { i = true, m = CONSTANTS.UIMAPIDS.SPOREFALL } },
		groupSize = 25,
		equalOdds = true,
	},
			--12.1 toys
	-- ["Jaktu's Cursed Blade"] = {
	-- 	cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
	-- 	type = CONSTANTS.ITEM_TYPES.ITEM,
	-- 	isToy = true,
	-- 	method = CONSTANTS.DETECTION_METHODS.USE,
	-- 	name = L["Jaktu's Cursed Blade"],
	-- 	itemId = 277954,
	-- 	items = 642071,
	-- 	chance = 1,
	-- 	sourceText = L["This item drops from the treasure Jaktu's Cursed Blade!"],
	-- 	coords = { { m = CONSTANTS.UIMAPIDS.COILED_ISLES } },
	-- },
	-- ["Ancient Amani Mask"] = {
	-- 	cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
	-- 	type = CONSTANTS.ITEM_TYPES.ITEM,
	-- 	istoy = true,
	-- 	method = CONSTANTS.DETECTION_METHODS.USE,
	-- 	name = L["Ancient Amani Mask"],
	-- 	itemId = 279052,
	-- 	item = 645208,
	-- 	chance = 1,
	-- 	sourceText = L["This item is looted from a chest named Sunken Diver's Chest and it requires a key named Diver's key, to get the key you need 3 fragments that are dropped off the rare named Ss'akrithos that spawns at the end of Mlurkkr massacre in Curse surge "],
	-- 	coords = { { m = CONSTANTS.UIMAPIDS.COILED_ISLES } },
	-- },
	-- ["Pearl of Jubilation"] = {
	-- 	cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
	-- 	type = CONSTANTS.ITEM_TYPES.ITEM,
	-- 	isToy = true,
	-- 	method = CONSTANTS.DETECTION_METHODS.USE,
	-- 	name = L["Pearl of Jubilation"],
	-- 	itemId = 274921,
	-- 	item = 649085,
	-- 	chance = 1,
	-- 	sourceText = L["Looted from a treasure named Brine-Crusted Chest"],
	-- 	coords = { { m = CONSTANTS.UIMAPIDS.COILED_ISLES } },
	-- },
	-- ["Forgotten Memento"] = {
	-- 	cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
	-- 	type = CONSTANTS.ITEM_TYPES.ITEM,
	-- 	isToy = true,
	-- 	method = CONSTANTS.DETECTION_METHODS.USE,
	-- 	name = L["Forgotten Memento"],
	-- 	itemId = 279021,
	-- 	item = 645549,
	-- 	chance = 1,
	-- 	sourceText = L["Looted from a treasure named Grave of Someone Forgotten"],
	-- 	coords = { { m = CONSTANTS.UIMAPIDS.COILED_ISLES } },
	-- },
	-- ["Malfunctioning Staff"] = {
	-- 	cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
	-- 	type = CONSTANTS.ITEM_TYPES.ITEM,
	-- 	isToy = true,
	-- 	method = CONSTANTS.DETECTION_METHODS.USE,
	-- 	name = L["Malfunctioning Staff"],
	-- 	itemId = 268504,
	-- 	item = 645550,
	-- 	chance = 1,
	-- 	sourceText = L["Looted from a treasure named Malfunctioning Staff"],
	-- 	coords = { { m = CONSTANTS.UIMAPIDS.COILED_ISLES } },
	-- },
	-- ["Idol of Blue Water and Blue Sky"] = {
	-- 	cat = CONSTANTS.ITEM_CATEGORIES.MIDNIGHT,
	-- 	type = CONSTANTS.ITEM_TYPES.ITEM,
	-- 	isToy = true,
	-- 	method = CONSTANTS.DETECTION_METHODS.USE,
	-- 	name = L["Idol of Blue Water and Blue Sky"],
	-- 	itemId = 279054,
	-- 	item = 619906,
	-- 	chance = 1,
	-- 	sourceText = L["Looted from a treasure named Abandoned Amani Privateer's Cache"],
	-- 	coords = { { m = CONSTANTS.UIMAPIDS.COILED_ISLES } },
	-- },

}

Rarity.ItemDB.MergeItems(Rarity.ItemDB.toys, midnightToys)
return midnightToys
